[debug] [2024-02-29T16:39:29.931Z] ----------------------------------------------------------------------
[debug] [2024-02-29T16:39:29.935Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\WALTON\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-02-29T16:39:29.936Z] CLI Version:   13.4.0
[debug] [2024-02-29T16:39:29.936Z] Platform:      win32
[debug] [2024-02-29T16:39:29.937Z] Node Version:  v18.17.0
[debug] [2024-02-29T16:39:29.939Z] Time:          Thu Feb 29 2024 22:39:29 GMT+0600 (Bangladesh Standard Time)
[debug] [2024-02-29T16:39:29.939Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-02-29T16:39:29.949Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] Already logged in as shahadathossain01954@gmail.com
[debug] [2024-02-29T16:39:32.010Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2024-02-29T16:39:32.012Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2024-02-29T16:39:40.121Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\WALTON\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:258:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
